/**
 * Per-module technique labels for display and TODO progress (master list).
 * Keys match module `id` in backend `modules.json` (e.g. ukemi). Technique names stay as authored.
 */
export const TECHNIQUE_LIST: Record<string, readonly string[]> = {
  ukemi: ['Ushiro Ukemi', 'Yoko Ukemi', 'Mae Mawari Ukemi'],

  'solo-newaza-workout': [
    'Soto Mawashi(Outside legs rotation)',
    'Uchi Mawashi(Inside legs rotation)',
    'Ashi Keri(Kicking the legs)',
    'Ashi Furi(swing legs)',
    'Ashi Kosa(cross legs)',
    '06',
    'Hane Age Koshi Nuki',
    'Koburi(small body shake)',
    'Forward bridge',
    'Backward bridge',
    '011',
    'Judo Pushup',
    'Fist pushup',
    '014',
    'No hands standup',
    'Shibori',
    'Shrimp',
    'Shrimp another side',
    '019',
    '020',
    'Aori',
    'Aori another side',
    'Twist',
    '024',
    '025',
    '026',
    'Koshi kiri inside',
    'Koshi kiri outside',
    'Fist pushup pause 2 seconds',
    'Static Shrimp',
    'Static Shrimp another side',
    '032',
    '033',
    '034',
    '035',
    'Static Aori',
    'Shibori Backward',
    'Shrimp with the leg inside',
    'Shrimp with the leg outside',
    'Plank walk side to side',
    '037',
  ],

  osaekomi: [
    'Kesa Gatame Basic',
    'Yoko Shiho Gatame Basic',
    'Kata Gatame Basic',
    'Mune Gatame',
    'Kami shiho Gatame',
    'Juji Gatame → Uki Gatame',
    'Kuzure Mune Gatame',
    'Around the world(15 Osaekomi Transitions)',
  ],

  'fundamental-tachi-waza': ['Basic Seoi Nage'],

  'kumikata-ai-yotsu': [
    'Win Kumikata in Ai Yotsu(same side grips)',
    'Simple Gripping in Ai Yotsu No.1 - No.3',
    'Simple Gripping in Ai Yotsu No.3 No.4',
    'Get Sleeve in Kenka Yotsu No1 - No.2',
    'Get Sleeve in Kenka Yotsu No.3 - No.4',
  ],

  'kumikata-kenka-yotsu': [
    'Win Kumikata in Kenka Yotsu(opposite side grips)',
    'Simple Gripping in Kenka Yotsu No.1 No.2 & No.2 Advance',
    'Simple Gripping in Kenka Yotsu No.3 No.4',
    'Simple Gripping in Ai Yotsu No.5 No.6',
    'Simple Gripping in Ai Yotsu No.7',
  ],

  'break-gripping-ai-yotsu': [
    'Breaking the Sleeve in Ai Yotsu',
    'Breaking the Collar in Ai Yotsu No.1',
    'Breaking the Collar in Ai Yotsu No.2',
  ],

  'break-gripping-kenka-yotsu': [
    'Breaking the Sleeve in Kenka Yotsu No.1 - No.3',
    'Breaking the Colloar in Kenka Yotsu',
    'Avoid His Tsuri Te(collar hand) in Kenka Yotsu',
  ],

  'kansetsu-waza': [
    'Transition Forward Technique → Juji',
    'JUJI GATAME Basic',
    'JUJI GATAME Setup (Take the wrist)',
    'JUJI GTAME → UKI GATAME',
    'JUJI GATAME → SANKAKU',
    'UDE GATAME No.1 (When he gets the pants)',
    'UDE GATAME No.2 (When he goes up the arm)',
    'UDE GATAME No.3',
    'Waki Gatame Variations',
    'Waki Gatame (When he gets the belt)',
    'HIZA GATAME with KOMUlock in Butterfly Guard',
    'TATE SHIHO GATAME & WAKI GATAME on the top with KOMUlock in Butterfly Guard',
    'WAKI GATAME with KOMUlock in Butterfly Guard',
    'KESA GATAME Armlock No.1 (ASHI GATAME)',
    'KESA GATAME Armlock (UDE GARAMI) No.2',
  ],

  'shime-waza': [
    'HADAKA JIME',
    'OKURI ERI JIME',
    'OKURI ERI JIME Escape No1',
    'KATA HA JIME',
    'OKURI ERI JIME Setup No1',
    'OKURI ERI JIME Setup No2',
    'OKURI ERI JIME Setup No3',
    'OKURI ERI JIME Setup No4',
    'JUJI GATAME → SANKAKU',
  ],

  'guard-pass-bottom': [
    'Scissors sweep No1',
    'Scissors sweep No2',
    'OBI TORI GAESHI in guard position',
    'UDE GATAME No.1 (When he gets the pants)',
    'UDE GATAME No.2 (When he goes up the arm)',
    'UDE GATAME No.3',
    'Butterfly Guard Drill No.1',
    'Butterfly Guard Drill No.2',
    'Butterfly Guard Drill No.3',
    'Butterfly Guard Drill No.4',
    'Butterfly Guard Drill No.5',
    'Butterfly Guard Drill No.6',
    'Butterfly Guard Drill No.7',
    'Butterfly Guard Drill No.8',
    'Cross Grip Turnover on the side in Butterfly Guard',
    'Cross Grip Turnover with SUMI GAESHI in Butterfly Guard',
    'HIZA GATAME with KOMUlock in Butterfly Guard',
    'TATE SHIHO GATAME & WAKI GATAME on the top with KOMUlock in Butterfly Guard',
    'WAKI GATAME with KOMUlock in Butterfly Guard',
    'WAKI JIME No.1',
    'WAKI JIME No.2',
    'WAKI JIME No.3',
    'KUSA KARI',
  ],

  'guard-pass-top': [
    'Guard Pass No1 (KESA GATME)',
    'Guard Pass No2 (KUZURE KESA GATME)',
    'Guard Pass No3 (YOKO SHIHO GATAME)',
    'Guard Pass No4 (TATE SHIHO GATME)',
    'Guard Pass No5 (Roll on the side)',
    'Guard Pass No6 (Flip)',
    'Kata Te Jime in JIGOKU ZEME',
    'Jigoku Zeme Gatame',
    'Kurimura Guard Pass No. 1',
    'Kurimura Guard Pass No. 2',
  ],

  'on-the-turtle': [
    'OBI TORI GAESHI on the turtle No.1',
    'OBI TORI GAESHI on the turtle (How To Take The Arm)',
    'OBI TORI GAESHI on the turtle No2',
    'OBI TORI GAESHI on the turtle No3',
    'OBI TORI GAESHI on the turtle No4',
    'KOSHI JIME Basic',
    'KOSHI JIME with pants (When he dies to stand up)',
  ],

  'escape-from-osaekomi': [
    'Kesa Gatame Escape No.1 (Push with the arm)',
    'Drill of Kesa Gatame Escape No.1',
    'Kesa Gatame Escape No.2 (Swing the legs)',
    'Kesa Gatame Escape No.3 (with Kobiri) + Koburi Video',
    'Kesa Gatame Escape No.4 (Push him on the stomach → Bring him another side',
    'KESA GATAME Escape No.5 Bring him another side with Bridges',
    'Kata Gatame escape No.1',
    'Kata Gatame escape No.2 (drill)',
    'YOKO SHIHO GATAME Escape No.1',
    'YOKO SHIHO GATAME Escape No.2',
  ],

  throwing: [
    'Kuchiki Daoshi Basic',
    'Single leg with O Uchi Gari',
    'Kibisu Gaeshi Basic',
    'Tornado Kibisu',
    'Morote Gari Basic',
    'Standing OBI TORI GAESHI (HIKIKOMI GAESHI) No.1',
    'Standing OBI TORI GAESHI (HIKIKOMI GAESHI) No.2',
    'Standing OBI TORI GAESHI (HIKIKOMI GAESHI) No.3',
    'Backward Techniques with Standing OBI TORI GAESHI (HIKIKOMI GAESHI)',
    'Standing OBI TORI GAESHI (HIKIKOMI GAESHI) Setup No.1 No.2',
    'Single Leg Counter with OBI TORI GAESHI (HIKIKOMI GAESHI)',
  ],

  'shime-waza-transition': [
    'KOSHI JIME Transition (SASAE → KOSHI JIME)',
    'Break Seoi Nage → Koshi Jime',
    'Uki Waza → Koshi Jime',
    'Sumi Gaeshi → Ashi Jime',
  ],

  'kansetsu-waza-transition': [
    'Transition No.4 Forward Technique → Juji',
    'Tomoe Nage → He resists → Juji',
    'Tomoe Nage → Juji',
    'He does Ashi Tori → avoid & break → Ashi Gatame',
    'Ude Tori Gaeshi → Te Gatame',
    'Tai Otoshi → get the arm → Ude Garami',
    'Kurimura Guard Pass No. 1',
  ],

  'osaekomi-transition': [
    'Morote Gari → Kuzure Kesa Gatame',
    'Transition No.1 Ko Uchi Gari → Sliding the knee → Kesa Gatame',
    'Transition No.2 O Uchi Gari → Koshi Kiri → Yoko Shiho Gatame',
    'Transition No.3 O Soto Gari → Catch the arm → go another side → Kuzure Mene Gatame',
    'Tawara Gaeshi → Osaekomi',
    'Morote Gari → Kami Shiho Gatame',
  ],
}
